# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 905d5156122afa4f417faae38ce55540af674c6b54812b3001a56a82c850b966fc431931bcf7dac74df1e0141e67f2fdbad5ff24bf295cb59c63aa41c9ffa0f3

test:
  secret_key_base: 5e8eac3b530b7e71d36312090102756d0be0539a01c395ab5ae449542b9df1333f88097281dd59207ae3aeb0dcc6b033d0660df399f5e3258490d687cd02c175

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
